# === App
spring.application.name=board-back
server.port=8080

# secret profile active
spring.profiles.active=secret,dev

spring.datasource.url=jdbc:mysql://localhost:3306/k7_iot_board


# === File upload === #
# Upload vase directory
file.upload.base-path=${user.dir}/upload

# Profile upload
file.upload.user-profile=user/profile

# Board upload root
file.upload.board=board

# Multipart settings
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=100MB